CREATE TABLE Propiedades (
    IdPropiedad          SERIAL NOT NULL,
    IdProveedor          INT               NOT NULL,
    IdTipoAlojamiento    INT               NOT NULL,
    IdZona               INT               NOT NULL,
    IdDistrito           INT               NULL,
    NombrePropiedad      VARCHAR (250)     NOT NULL,
    TituloPromocional    VARCHAR (200)     NULL,
    DescripcionLarga     VARCHAR (2000)    NOT NULL,
    DescripcionCorta     VARCHAR (300)     NULL,
    UbicacionDetallada   VARCHAR (300)     NOT NULL,
    Coordenadas          GEOGRAPHY(POINT, 4326) NULL,
    CantidadHabitaciones INT               NOT NULL,
    CantidadCamas        INT               NOT NULL,
    CapacidadMaxima      INT               NOT NULL,
    CantidadBanios       INT               DEFAULT 1 NOT NULL,
    AreaMetrosCuadrados  INT               NULL,
    MontoXNoche          DECIMAL (18, 2)   NOT NULL,
    Moneda               INT               DEFAULT 1 NOT NULL,
    DepositoGarantia     DECIMAL (18, 2)   NULL,
    IdEstado             INT               NOT NULL,
    Verificado           BOOLEAN               DEFAULT FALSE NULL,
    FechaRegistro        TIMESTAMP          DEFAULT CURRENT_TIMESTAMP NULL,
    FechaActualizacion   TIMESTAMP          NULL,
    VecesVisto           INT               DEFAULT 0 NULL,
    RatingPromedio       DECIMAL (3, 2)    DEFAULT 0 NULL,
    TotalResenas         INT               DEFAULT 0 NULL,
    PRIMARY KEY (IdPropiedad),
    CHECK (CantidadCamas>(0)),
    CHECK (CantidadHabitaciones>(0)),
    CHECK (CapacidadMaxima>(0)),
    CHECK (MontoXNoche>(0)),
    FOREIGN KEY (IdDistrito) REFERENCES Distritos (IdDistrito),
    FOREIGN KEY (IdEstado) REFERENCES Estados (IdEstado),
    FOREIGN KEY (IdProveedor) REFERENCES Usuarios (IdUsuario),
    FOREIGN KEY (IdTipoAlojamiento) REFERENCES TipoAlojamiento (IdTipo),
    FOREIGN KEY (IdZona) REFERENCES ZonasTicas (IdZona),
    FOREIGN KEY (Moneda) REFERENCES Monedas (IdMoneda)
);


