import uuid

def unique_id():
    return uuid.uuid4().hex[:8]


class EntityDef:
    def __init__(self, name, endpoint, pk_field, sample_fn, dependent_fks=None, composite=False, no_put=False):
        self.name = name
        self.endpoint = endpoint
        self.pk_field = pk_field
        self.sample_fn = sample_fn
        self.dependent_fks = dependent_fks or []
        self.composite = composite
        self.no_put = no_put


def _uid():
    return abs(hash(uuid.uuid4())) % 900000 + 100000


ENTITIES = [
    # ---- Level 0: No FK dependencies ----
    EntityDef("Provincias", "Provincias", "idProvincia", lambda ctx: {
        "idProvincia": 0,
        "nombreProvincia": f"Prov_{unique_id()}",
        "activo": True,
    }),
    EntityDef("Estados", "Estados", "idEstado", lambda ctx: {
        "idEstado": 0,
        "nombreEstado": f"Est_{unique_id()}",
        "tipoEntidad": "General",
    }),
    EntityDef("Roles", "Roles", "idRol", lambda ctx: {
        "idRol": 0,
        "nombreRol": f"Rol_{unique_id()}",
        "descripcion": "Rol de prueba",
    }),
    EntityDef("Nacionalidades", "Nacionalidades", "idNacionalidad", lambda ctx: {
        "idNacionalidad": 0,
        "nacionalidad": f"Nac_{unique_id()}",
        "codigoISO": unique_id()[:2],
        "activo": True,
    }),
    EntityDef("CategoriasFAQ", "CategoriasFAQ", "idCategoriaFAQ", lambda ctx: {
        "idCategoriaFAQ": 0,
        "nombreCategoria": f"CatFAQ_{unique_id()}",
        "descripcion": "Categoria de prueba",
        "orden": 1,
        "activo": True,
    }),
    EntityDef("ComerciosCercanos", "ComerciosCercanos", "idComercio", lambda ctx: {
        "idComercio": 0,
        "nombreComercio": f"Com_{unique_id()}",
        "tipoComercio": "Supermercado",
        "telefono": "2255-5555",
        "direccion": "Calle Principal",
        "horarioAtencion": "8am-6pm",
        "activo": True,
    }),
    EntityDef("PoliticasCancelacion", "PoliticasCancelacion", "idPolitica", lambda ctx: {
        "idPolitica": 0,
        "nombrePolitica": f"Pol_{unique_id()}",
        "descripcion": "Politica de prueba",
        "reembolsoPorcentaje": 50.00,
        "diasAntelacion": 3,
        "activo": True,
    }),
    EntityDef("Promociones", "Promociones", "idPromocion", lambda ctx: {
        "idPromocion": 0,
        "nombrePromo": f"Promo_{unique_id()}",
        "descripcion": "Promocion de prueba",
        "tipoPromo": "TemporadaBaja",
        "porcentajeDescuento": 10.00,
        "fechaInicio": "2026-01-01",
        "fechaFin": "2026-12-31",
        "activo": True,
    }),
    EntityDef("ReglasCasa", "ReglasCasa", "idRegla", lambda ctx: {
        "idRegla": 0,
        "nombreRegla": f"Regla_{unique_id()}",
        "descripcion": "Regla de prueba",
        "icono": "rule",
    }),
    EntityDef("TransporteCercano", "TransporteCercano", "idTransporte", lambda ctx: {
        "idTransporte": 0,
        "tipoTransporte": "Parada de Bus",
        "nombre": f"Trans_{unique_id()}",
        "distanciaReferencia": "200m",
        "telefono": "2222-2222",
    }),
    EntityDef("ZonasTicas", "ZonasTicas", "idZona", lambda ctx: {
        "idZona": 0,
        "nombreZona": f"Zona_{unique_id()}",
        "descripcion": "Zona de prueba",
        "activo": True,
    }),
    EntityDef("NewsletterSuscriptores", "NewsletterSuscriptores", "idSuscriptor", lambda ctx: {
        "idSuscriptor": 0,
        "correo": f"{unique_id()}@test.com",
        "nombre": "Suscriptor Test",
        "activo": True,
        "tokenCancelacion": unique_id(),
    }),
    # Equipamiento depends on seed table CategoriaEquipamiento (idCategoria=1)
    EntityDef("Equipamiento", "Equipamiento", "idEquipamiento", lambda ctx: {
        "idEquipamiento": 0,
        "idCategoria": 1,
        "nombreEquipamiento": f"Equip_{unique_id()}",
        "descripcion": "Equipamiento de prueba",
        "icono": "gear",
        "activo": True,
    }),
    # ---- Level 1: Depend on Level 0 ----
    EntityDef("Cantones", "Cantones", "idCanton", lambda ctx: {
        "idCanton": 0,
        "idProvincia": ctx["idProvincia"],
        "nombreCanton": f"Canton_{unique_id()}",
        "activo": True,
    }, dependent_fks=["Provincias"]),
    EntityDef("FAQs", "FAQs", "idFAQ", lambda ctx: {
        "idFAQ": 0,
        "idCategoriaFAQ": ctx["idCategoriaFAQ"],
        "pregunta": f"Pregunta_{unique_id()}?",
        "respuesta": "Respuesta de prueba",
        "orden": 1,
        "vecesVista": 0,
        "activo": True,
        "creadoPor": ctx["idUsuario"],
        "fechaCreacion": "2026-07-13T00:00:00",
        "modificadoPor": None,
        "fechaModificacion": None,
    }, dependent_fks=["CategoriasFAQ", "Usuarios"]),
    # ---- Level 2: Depend on Level 1 ----
    EntityDef("Distritos", "Distritos", "idDistrito", lambda ctx: {
        "idDistrito": 0,
        "idCanton": ctx["idCanton"],
        "nombreDistrito": f"Dist_{unique_id()}",
        "codigoPostal": "10000",
        "activo": True,
    }, dependent_fks=["Cantones"]),
    EntityDef("Usuarios", "Usuarios", "idUsuario", lambda ctx: {
        "idUsuario": _uid(),
        "nombre": "Maria",
        "primerApellido": "Lopez",
        "segundoApellido": "Garcia",
        "correo": f"{unique_id()}@test.com",
        "contrasena": "hashed_abc123",
        "idNacionalidad": ctx["idNacionalidad"],
        "direccion": "Calle Principal 123",
        "idDistrito": ctx.get("idDistrito"),
        "fechaNacimiento": "1990-05-15T00:00:00",
        "genero": "F",
        "idRol": ctx["idRol"],
        "idEstado": ctx["idEstado"],
        "fechaRegistro": "2026-07-13T00:00:00",
        "ultimoAcceso": None,
        "emailConfirmado": True,
        "telefonoConfirmado": False,
        "fotoPerfil": None,
        "notasInternas": "Usuario de prueba",
    }, dependent_fks=["Provincias", "Cantones", "Distritos", "Nacionalidades", "Roles", "Estados"]),
    # ---- Level 3a: Depend on Usuarios only ----
    EntityDef("ListasDeseos", "ListasDeseos", "idLista", lambda ctx: {
        "idLista": 0,
        "idUsuario": ctx["idUsuario"],
        "nombreLista": f"Lista_{unique_id()}",
        "fechaCreacion": "2026-07-13T00:00:00",
        "privada": True,
    }, dependent_fks=["Usuarios"]),
    EntityDef("Sesiones", "Sesiones", "idSesion", lambda ctx: {
        "idSesion": 0,
        "idUsuario": ctx["idUsuario"],
        "token": f"tok_{unique_id()}",
        "fechaInicio": "2026-07-13T00:00:00",
        "fechaExpiracion": "2026-12-31T00:00:00",
        "ipAddress": "127.0.0.1",
        "userAgent": "Test/1.0",
        "activa": True,
    }, dependent_fks=["Usuarios"]),
    EntityDef("TelefonosUsuarios", "TelefonosUsuarios", "idTelefono", lambda ctx: {
        "idTelefono": 0,
        "idUsuario": ctx["idUsuario"],
        "telefono": "8888-8888",
        "tipoTelefono": "Celular",
        "esPrincipal": True,
        "activo": True,
    }, dependent_fks=["Usuarios"]),
    EntityDef("CorreosUsuarios", "CorreosUsuarios", "idCorreo", lambda ctx: {
        "idCorreo": 0,
        "idUsuario": ctx["idUsuario"],
        "correo": f"{unique_id()}@alternativo.com",
        "esPrincipal": False,
        "activo": True,
    }, dependent_fks=["Usuarios"]),
    EntityDef("VerificacionesUsuarios", "VerificacionesUsuarios", "idVerificacion", lambda ctx: {
        "idVerificacion": 0,
        "idUsuario": ctx["idUsuario"],
        "tipoVerificacion": "Correo",
        "verificado": True,
        "fechaVerificacion": "2026-07-13T00:00:00",
        "metodoVerificacion": "codigo",
    }, dependent_fks=["Usuarios"]),
    EntityDef("RecuperacionContrasenas", "RecuperacionContrasenas", "idSolicitud", lambda ctx: {
        "idSolicitud": 0,
        "idUsuario": ctx["idUsuario"],
        "token": f"reset_{unique_id()}",
        "fechaSolicitud": "2026-07-13T00:00:00",
        "fechaExpiracion": "2026-07-14T00:00:00",
        "usada": False,
    }, dependent_fks=["Usuarios"]),
    # ---- Level 3b: Depend on Usuarios + Estados ----
    EntityDef("TicketsSoporte", "TicketsSoporte", "idTicket", lambda ctx: {
        "idTicket": 0,
        "idUsuario": ctx["idUsuario"],
        "asunto": f"Asunto_{unique_id()}",
        "descripcion": "Descripcion del ticket de prueba",
        "idEstado": ctx["idEstado"],
        "prioridad": "Media",
        "fechaCreacion": "2026-07-13T00:00:00",
        "fechaCierre": None,
        "idAgenteAsignado": None,
    }, dependent_fks=["Usuarios", "Estados"]),
    EntityDef("MensajesSoporte", "MensajesSoporte", "idMensaje", lambda ctx: {
        "idMensaje": 0,
        "idTicket": ctx["idTicket"],
        "idUsuario": ctx["idUsuario"],
        "mensaje": "Mensaje de prueba para el ticket",
        "fechaEnvio": "2026-07-13T00:00:00",
        "adjuntoURL": None,
    }, dependent_fks=["TicketsSoporte", "Usuarios"]),
    EntityDef("Reportes", "Reportes", "idReporte", lambda ctx: {
        "idReporte": 0,
        "idUsuarioReporta": ctx["idUsuario"],
        "idUsuarioReportado": None,
        "idPropiedadReportada": None,
        "idReservaRelacionada": None,
        "motivo": "Spam",
        "descripcion": "Reporte de prueba",
        "fechaReporte": "2026-07-13T00:00:00",
        "idEstado": ctx["idEstado"],
        "resolucion": None,
        "fechaResolucion": None,
        "resueltoPor": None,
    }, dependent_fks=["Usuarios", "Estados"]),
    EntityDef("EvidenciasReporte", "EvidenciasReporte", "idEvidencia", lambda ctx: {
        "idEvidencia": 0,
        "idReporte": ctx["idReporte"],
        "tipoEvidencia": "Foto",
        "urlArchivo": f"http://example.com/evidencia_{unique_id()}.jpg",
        "descripcion": "Evidencia de prueba",
        "fechaSubida": "2026-07-13T00:00:00",
    }, dependent_fks=["Reportes"]),
    # ---- Level 3c: Depend on Propiedades (which depend on Usuarios + Estados + seed) ----
    EntityDef("Propiedades", "Propiedades", "idPropiedad", lambda ctx: {
        "idPropiedad": 0,
        "idProveedor": ctx["idUsuario"],
        "idTipoAlojamiento": 1,
        "idZona": 1,
        "idDistrito": ctx.get("idDistrito"),
        "nombrePropiedad": f"Prop_{unique_id()}",
        "tituloPromocional": "Bonita propiedad",
        "descripcionLarga": "Hermosa propiedad con vista al mar",
        "descripcionCorta": "Vista al mar",
        "ubicacionDetallada": "Costa Rica, Puntarenas",
        "cantidadHabitaciones": 3,
        "cantidadCamas": 4,
        "capacidadMaxima": 6,
        "cantidadBanios": 2,
        "areaMetrosCuadrados": 150,
        "montoXNoche": 75.00,
        "moneda": 1,
        "depositoGarantia": 50.00,
        "idEstado": ctx["idEstado"],
        "verificado": False,
        "fechaRegistro": "2026-07-13T00:00:00",
        "fechaActualizacion": None,
        "vecesVisto": 0,
        "ratingPromedio": None,
        "totalResenas": 0,
    }, dependent_fks=["Usuarios", "Estados"]),
    EntityDef("FotosPropiedads", "FotosPropiedads", "idFoto", lambda ctx: {
        "idFoto": 0,
        "idPropiedad": ctx["idPropiedad"],
        "urlFoto": f"http://example.com/foto_{unique_id()}.jpg",
        "titulo": "Foto de prueba",
        "descripcion": "Foto principal",
        "orden": 1,
        "esPrincipal": True,
        "fechaSubida": "2026-07-13T00:00:00",
        "activo": True,
    }, dependent_fks=["Propiedades"]),
    EntityDef("HorariosCheckInOut", "HorariosCheckInOut", "idHorario", lambda ctx: {
        "idHorario": 0,
        "idPropiedad": ctx["idPropiedad"],
        "tipoHorario": "CheckIn",
        "horaDesde": "14:00:00",
        "horaHasta": "20:00:00",
        "flexible": False,
        "notas": "Horario estandar",
    }, dependent_fks=["Propiedades"]),
    # ---- Level 3d: Reservas + dependents (Pagos, Calificaciones) ----
    EntityDef("Reservas", "Reservas", "idReserva", lambda ctx: {
        "idReserva": 0,
        "idCliente": ctx["idUsuario"],
        "idPropiedad": ctx["idPropiedad"],
        "fechaEntrada": "2026-08-01",
        "fechaSalida": "2026-08-05",
        "cantidadPersonas": 2,
        "cantidadNoches": 4,
        "precioPorNoche": 75.00,
        "subtotal": 300.00,
        "descuentoAplicado": 0.00,
        "comision": 30.00,
        "total": 270.00,
        "idEstado": ctx["idEstado"],
        "fechaReserva": "2026-07-13T00:00:00",
        "notasCliente": "Notas de prueba",
        "notasInternas": None,
    }, dependent_fks=["Usuarios", "Propiedades", "Estados"]),
    EntityDef("Pagos", "Pagos", "idPago", lambda ctx: {
        "idPago": 0,
        "idReserva": ctx["idReserva"],
        "montoCRC": 270.00,
        "montoUSD": None,
        "fechaPago": "2026-07-13T00:00:00",
        "metodoPago": "Tarjeta",
        "estadoPago": "Completado",
        "comprobanteURL": None,
        "telefonoSINPE": None,
        "referenciaBanco": None,
        "idUsuarioRegistra": ctx["idUsuario"],
    }, dependent_fks=["Reservas", "Usuarios"]),
    EntityDef("CalificacionesPropiedad", "CalificacionesPropiedad", "idCalificacion", lambda ctx: {
        "idCalificacion": 0,
        "idReserva": ctx["idReserva"],
        "idCliente": ctx["idUsuario"],
        "idPropiedad": ctx["idPropiedad"],
        "calificacion": 5,
        "comentario": "Excelente propiedad, muy recomendada",
        "fecha": "2026-08-06T00:00:00",
        "visible": True,
    }, dependent_fks=["Reservas", "Usuarios", "Propiedades"]),
    # ---- Composite-key entities ----
    EntityDef("ListaPropiedades", "ListaPropiedades", ["idLista", "idPropiedad"], lambda ctx: {
        "idLista": ctx["idLista"],
        "idPropiedad": ctx["idPropiedad"],
        "fechaAgregado": "2026-07-13T00:00:00",
    }, dependent_fks=["ListasDeseos", "Propiedades"], composite=True),
    EntityDef("PromocionesPropiedad", "PromocionesPropiedad", ["idPromocion", "idPropiedad"], lambda ctx: {
        "idPromocion": ctx["idPromocion"],
        "idPropiedad": ctx["idPropiedad"],
    }, dependent_fks=["Promociones", "Propiedades"], composite=True, no_put=True),
    EntityDef("PropiedadEquipamiento", "PropiedadEquipamiento", ["idPropiedad", "idEquipamiento"], lambda ctx: {
        "idPropiedad": ctx["idPropiedad"],
        "idEquipamiento": ctx["idEquipamiento"],
        "cantidad": 1,
        "descripcionAdicional": None,
    }, dependent_fks=["Propiedades", "Equipamiento"], composite=True),
    EntityDef("PropiedadReglas", "PropiedadReglas", ["idPropiedad", "idRegla"], lambda ctx: {
        "idPropiedad": ctx["idPropiedad"],
        "idRegla": ctx["idRegla"],
        "esAplicable": True,
        "detalleEspecifico": None,
    }, dependent_fks=["Propiedades", "ReglasCasa"], composite=True),
    EntityDef("PropiedadServicios", "PropiedadServicios", ["idPropiedad", "idServicio"], lambda ctx: {
        "idPropiedad": ctx["idPropiedad"],
        "idServicio": 1,
        "descripcionAdicional": None,
        "incluidoEnPrecio": True,
    }, dependent_fks=["Propiedades"], composite=True),
]
