CREATE TABLE [dbo].[Usuarios] (
    [IdUsuario]          INT           NOT NULL,
    [Nombre]             VARCHAR (100) NOT NULL,
    [PrimerApellido]     VARCHAR (100) NOT NULL,
    [SegundoApellido]    VARCHAR (100) NULL,
    [Correo]             VARCHAR (100) NOT NULL,
    [Contrasena]         VARCHAR (255) NOT NULL,
    [IdNacionalidad]     INT           NOT NULL,
    [Direccion]          VARCHAR (300) NOT NULL,
    [IdDistrito]         INT           NULL,
    [FechaNacimiento]    DATE          NULL,
    [Genero]             CHAR (1)      NULL,
    [IdRol]              INT           NOT NULL,
    [IdEstado]           INT           NOT NULL,
    [FechaRegistro]      DATETIME      DEFAULT (getdate()) NULL,
    [UltimoAcceso]       DATETIME      NULL,
    [EmailConfirmado]    BIT           DEFAULT ((0)) NULL,
    [TelefonoConfirmado] BIT           DEFAULT ((0)) NULL,
    [FotoPerfil]         VARCHAR (500) NULL,
    [NotasInternas]      VARCHAR (500) NULL,
    PRIMARY KEY CLUSTERED ([IdUsuario] ASC),
    CHECK ([Genero]='O' OR [Genero]='F' OR [Genero]='M'),
    FOREIGN KEY ([IdDistrito]) REFERENCES [dbo].[Distritos] ([IdDistrito]),
    FOREIGN KEY ([IdEstado]) REFERENCES [dbo].[Estados] ([IdEstado]),
    FOREIGN KEY ([IdNacionalidad]) REFERENCES [dbo].[Nacionalidades] ([IdNacionalidad]),
    FOREIGN KEY ([IdRol]) REFERENCES [dbo].[Roles] ([IdRol]),
    UNIQUE NONCLUSTERED ([Correo] ASC)
);

