CREATE TABLE [dbo].[Propiedades] (
    [IdPropiedad]          INT               IDENTITY (1, 1) NOT NULL,
    [IdProveedor]          INT               NOT NULL,
    [IdTipoAlojamiento]    INT               NOT NULL,
    [IdZona]               INT               NOT NULL,
    [IdDistrito]           INT               NULL,
    [NombrePropiedad]      VARCHAR (250)     NOT NULL,
    [TituloPromocional]    VARCHAR (200)     NULL,
    [DescripcionLarga]     VARCHAR (2000)    NOT NULL,
    [DescripcionCorta]     VARCHAR (300)     NULL,
    [UbicacionDetallada]   VARCHAR (300)     NOT NULL,
    [Coordenadas]          [sys].[geography] NULL,
    [CantidadHabitaciones] INT               NOT NULL,
    [CantidadCamas]        INT               NOT NULL,
    [CapacidadMaxima]      INT               NOT NULL,
    [CantidadBanios]       INT               DEFAULT ((1)) NOT NULL,
    [AreaMetrosCuadrados]  INT               NULL,
    [MontoXNoche]          DECIMAL (18, 2)   NOT NULL,
    [Moneda]               INT               DEFAULT ((1)) NOT NULL,
    [DepositoGarantia]     DECIMAL (18, 2)   NULL,
    [IdEstado]             INT               NOT NULL,
    [Verificado]           BIT               DEFAULT ((0)) NULL,
    [FechaRegistro]        DATETIME          DEFAULT (getdate()) NULL,
    [FechaActualizacion]   DATETIME          NULL,
    [VecesVisto]           INT               DEFAULT ((0)) NULL,
    [RatingPromedio]       DECIMAL (3, 2)    DEFAULT ((0)) NULL,
    [TotalResenas]         INT               DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([IdPropiedad] ASC),
    CHECK ([CantidadCamas]>(0)),
    CHECK ([CantidadHabitaciones]>(0)),
    CHECK ([CapacidadMaxima]>(0)),
    CHECK ([MontoXNoche]>(0)),
    FOREIGN KEY ([IdDistrito]) REFERENCES [dbo].[Distritos] ([IdDistrito]),
    FOREIGN KEY ([IdEstado]) REFERENCES [dbo].[Estados] ([IdEstado]),
    FOREIGN KEY ([IdProveedor]) REFERENCES [dbo].[Usuarios] ([IdUsuario]),
    FOREIGN KEY ([IdTipoAlojamiento]) REFERENCES [dbo].[TipoAlojamiento] ([IdTipo]),
    FOREIGN KEY ([IdZona]) REFERENCES [dbo].[ZonasTicas] ([IdZona]),
    FOREIGN KEY ([Moneda]) REFERENCES [dbo].[Monedas] ([IdMoneda])
);

